FORMAT: 1A

# Erweiterung
Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor
invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et
accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata
sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur
sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna
aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea
rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit
amet.

# User1
User1 ...

## Login [POST /user1/login]
Login with username and password.

+ Request (application/json)
    + Attributes (object)
        + username: Peter (string, required)
        + password: 1234Hallo (string, required)

+ Response 200 (application/json)
    + Attributes (object)
        + token: wn5934zn5vc973n4zc5384z5tzn349nzt3 (string, required)

## Logout [POST /user1/logout]
Logout.

+ Request
    + Headers
        Authorization: Bearer <token>

+ Response 200 (application/json)
    + Attributes (object)

## Get classification [GET /user1/get-classification]
Get classification.

+ Request
    + Headers
        Authorization: Bearer <token>

+ Response 200 (application/json)
    + Attributes (object)
        + result: true (boolean, required)
        + kind (enum)
            + A
            + B
