FORMAT: 1A

# Erweiterung
Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor
invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et
accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata
sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur
sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna
aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea
rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit
amet.

# User1 [/user1]
User1 ...

## Login [POST /login]
Login with username and password.

+ Request (application/json)
    + Body
        {
            "username": "Peter",
            "password": "1234Hallo"
        }

    + Schema

            {
                "type": "object",
                "properties": {
                    "username": {
                        "type": "string"
                    },
                    "password": {
                        "type": "string"
                    }
                }
            }

+ Response 200 (application/json)

    + Body

            {
                "token": "wn5934zn5vc973n4zc5384z5tzn349nzt3"
            }

    + Schema

            {
                "type": "object",
                "properties": {
                    "token": {
                        "type": "string"
                    }
                }
            }

## Logout [POST /logout]
Logout.

+ Request

    + Headers

            Authorization: Bearer <token>

+ Response 200 (application/json)

    + Body

            {
                
            }

    + Schema

            {
                "type": "object",
                "properties": {
                    
                }
            }

## Get classification [GET /get-classification]
Get classification.

+ Request

    + Headers

            Authorization: Bearer <token>

+ Response 200 (application/json)

    + Attributes (object)
        + id: 250FF (string, required)
        + created: 1415203908 (number) - Time stamp
        + percent_off: 25 (number)

            A positive integer between 1 and 100 that represents the discount
            the coupon will apply.

        + redeem_by (number) - Date after which the coupon can no longer be redeemed

    + Body

            {
                result: true
            }

    + Schema

            {
                "type": "object",
                "properties": {
                    "result": {
                        "type": "boolean"
                    }
                }
            }